options:
  formatter: stylish
files:
	include: '**/*.s+(a|c)ss'
rules:
	# Disallows
  no-ids: 2
  no-important: 1
  no-css-comments: 0
  no-vendor-prefixes: 0
  no-url-domains: 0
  no-url-protocols: 0

  # Style Guide
  empty-args: 0
  pseudo-element: 0
  nesting-depth: 3
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  indentation:
    - 2
    -
      size: tab